apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: notification-manager-leader-election-rolebinding
  namespace: kubesphere-monitoring-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: notification-manager-leader-election-role
subjects:
- kind: ServiceAccount
  name: notification-manager-sa
  namespace: kubesphere-monitoring-system
  