apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: notification-manager-controller-metrics
  namespace: kubesphere-monitoring-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
  sessionAffinity: None
  type: ClusterIP
  