
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXekNDQWtPZ0F3SUJBZ0lVWVRnYkxtTVQ3VzMwZkxRZWh5R3c2R09KTmlJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1BERUxNQWtHQTFVRUJoTUNRMDR4Q3pBSkJnTlZCQWdNQWtoQ01Rc3dDUVlEVlFRS0RBSlJRekVUTUJFRwpBMVVFQXd3S2QyVmlhRzl2YXkxallUQWdGdzB5TVRBM01qRXhNREl4TkRKYUdBOHlNVEl4TURZeU56RXdNakUwCk1sb3dQREVMTUFrR0ExVUVCaE1DUTA0eEN6QUpCZ05WQkFnTUFraENNUXN3Q1FZRFZRUUtEQUpSUXpFVE1CRUcKQTFVRUF3d0tkMlZpYUc5dmF5MWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQgpBTDV4c0NLRVFWYWU2bXVoN2F0MXpmeW52MnRNQWpMWERMUkJEL01CVURKK2Q0RVFBbmtOeU9FK2ZOYTlBaTZSCmdYcUJ4SFJORG9vMXBmS2E0MU9zYlU2Q0hYNEVpbkJySUxYdFQ4QjZCTXI1Sk41cVpMdUpZSktObHlsTnBtVWgKRTVDeHNJb3FVdWJQZTNVMHA1S3VlY0ZBam4xOCtkbkt5bEg2L05lNnY2c2dxQ3V3ZVo4cEwydlA3RmJLZ1N4YgpBaXZheVkvS3ZHcTR4Ry9qd2xDaXFsK3JYbE91MUZYWGJFdTNkOWhUdTl5V256cEZERDdZbnNNTFA5SUhUWUhKCmJJTmVMYjJTbHRXcGpld3dHNkgrQlEzOUNmeW1rZlRidG43VTVLZU5Yc2xiTlJZcUt0bDFpdjhKRHJkaTFNNE8KRkZWanBoMHVaYkFzTXpIczFyWnpzVEVDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkpOczN2WXJVQmN2WTYwSApIbXpjaWo3RXN5YitNQjhHQTFVZEl3UVlNQmFBRkpOczN2WXJVQmN2WTYwSEhtemNpajdFc3liK01BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQTlpazgwZkx2d3YrQmlOWHpScWNrRTIKMXlGbkp1eEhZU3dobGMyRkNiZHc3eTV5Uk5ZVjRDTHJlNmJrRUViZnpxWU52MEF2amhxRWxVWmNjK0Jla2NDOQpnSnNvWS96VnJMcVFlV1VHNExOS3pyWUNSMm9KOW5WNTFyQ290N2NCUmtSQkcxMldCSENhOGZGblV6R2JZbTlaCmtHQ3p6WHAxeW9MNkFnVk9zak5kUE9XUDFYYzdDdlcwZlNLS0xtV3pwQ25qWjZPMGdFSlhJeml4RE9PNXl5MjkKUzNUaDNPNmxYdG1aUTlGVzdqMi90bHloVGc3azBkRnVuaGVoVWx4VDhqaE54NWVsNDA2ZGVrNzc5c3ZpL3MrZAo1T3MwQzdDdDhmMFVnRVlHMm9rTFdiSkRBM2t6UU9NNHlQQ1Z6aEo5aVRLYkZVOGFmUGwyd0dxeWhvaDZyUms9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: webhook
      namespace: system
      path: /validate-notification-kubesphere-io-v2beta2-config
  failurePolicy: Fail
  name: vconfig.notification.kubesphere.io
  rules:
  - apiGroups:
    - notification.kubesphere.io
    apiVersions:
    - v2beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - configs
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXekNDQWtPZ0F3SUJBZ0lVWVRnYkxtTVQ3VzMwZkxRZWh5R3c2R09KTmlJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1BERUxNQWtHQTFVRUJoTUNRMDR4Q3pBSkJnTlZCQWdNQWtoQ01Rc3dDUVlEVlFRS0RBSlJRekVUTUJFRwpBMVVFQXd3S2QyVmlhRzl2YXkxallUQWdGdzB5TVRBM01qRXhNREl4TkRKYUdBOHlNVEl4TURZeU56RXdNakUwCk1sb3dQREVMTUFrR0ExVUVCaE1DUTA0eEN6QUpCZ05WQkFnTUFraENNUXN3Q1FZRFZRUUtEQUpSUXpFVE1CRUcKQTFVRUF3d0tkMlZpYUc5dmF5MWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQgpBTDV4c0NLRVFWYWU2bXVoN2F0MXpmeW52MnRNQWpMWERMUkJEL01CVURKK2Q0RVFBbmtOeU9FK2ZOYTlBaTZSCmdYcUJ4SFJORG9vMXBmS2E0MU9zYlU2Q0hYNEVpbkJySUxYdFQ4QjZCTXI1Sk41cVpMdUpZSktObHlsTnBtVWgKRTVDeHNJb3FVdWJQZTNVMHA1S3VlY0ZBam4xOCtkbkt5bEg2L05lNnY2c2dxQ3V3ZVo4cEwydlA3RmJLZ1N4YgpBaXZheVkvS3ZHcTR4Ry9qd2xDaXFsK3JYbE91MUZYWGJFdTNkOWhUdTl5V256cEZERDdZbnNNTFA5SUhUWUhKCmJJTmVMYjJTbHRXcGpld3dHNkgrQlEzOUNmeW1rZlRidG43VTVLZU5Yc2xiTlJZcUt0bDFpdjhKRHJkaTFNNE8KRkZWanBoMHVaYkFzTXpIczFyWnpzVEVDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkpOczN2WXJVQmN2WTYwSApIbXpjaWo3RXN5YitNQjhHQTFVZEl3UVlNQmFBRkpOczN2WXJVQmN2WTYwSEhtemNpajdFc3liK01BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQTlpazgwZkx2d3YrQmlOWHpScWNrRTIKMXlGbkp1eEhZU3dobGMyRkNiZHc3eTV5Uk5ZVjRDTHJlNmJrRUViZnpxWU52MEF2amhxRWxVWmNjK0Jla2NDOQpnSnNvWS96VnJMcVFlV1VHNExOS3pyWUNSMm9KOW5WNTFyQ290N2NCUmtSQkcxMldCSENhOGZGblV6R2JZbTlaCmtHQ3p6WHAxeW9MNkFnVk9zak5kUE9XUDFYYzdDdlcwZlNLS0xtV3pwQ25qWjZPMGdFSlhJeml4RE9PNXl5MjkKUzNUaDNPNmxYdG1aUTlGVzdqMi90bHloVGc3azBkRnVuaGVoVWx4VDhqaE54NWVsNDA2ZGVrNzc5c3ZpL3MrZAo1T3MwQzdDdDhmMFVnRVlHMm9rTFdiSkRBM2t6UU9NNHlQQ1Z6aEo5aVRLYkZVOGFmUGwyd0dxeWhvaDZyUms9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: webhook
      namespace: system
      path: /validate-notification-kubesphere-io-v2beta2-receiver
  failurePolicy: Fail
  name: vreceiver.notification.kubesphere.io
  rules:
  - apiGroups:
    - notification.kubesphere.io
    apiVersions:
    - v2beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - receivers
