
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXekNDQWtPZ0F3SUJBZ0lVVG9uSE1YaFAzc2ljVHpQRHFmN1hmY2lLR1BZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1BERUxNQWtHQTFVRUJoTUNRMDR4Q3pBSkJnTlZCQWdNQWtoQ01Rc3dDUVlEVlFRS0RBSlJRekVUTUJFRwpBMVVFQXd3S2QyVmlhRzl2YXkxallUQWdGdzB5TVRBME1qRXdNalV5TlRsYUdBOHlNVEl4TURNeU9EQXlOVEkxCk9Wb3dQREVMTUFrR0ExVUVCaE1DUTA0eEN6QUpCZ05WQkFnTUFraENNUXN3Q1FZRFZRUUtEQUpSUXpFVE1CRUcKQTFVRUF3d0tkMlZpYUc5dmF5MWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQgpBSitpTWZQRld2dndWSmU1cUNBTWJlcnpaL0dLdFllZ3JRUlhES09nN1FKaE9nSWd5d25pKzVDM3VPM21JTE1hClRCWTkvcCtZM2d4akduUnJUWGNkcFB5ZG1BUDNyK2Y0Tm5TL3ZQa21XMm9mQzFNWEJNSUNUK1hFR3dIRExjWUgKR2hDWVBYcWVTZHVVTEJtTXFtYzFFNDB6ekRGcmpWTzltLzZFbjh0dVN3RmFaSVRnNUsvcm5Ld0UzdlNoazVYNApqVWdSYTF1Ym9nZHd1THFDTGRFWVB4MDdHUHdZb3JXQnlveXllYmNXRlBqRXRJSCtKWFRGQ2w0VDNXYkZhUUthCmxLOTY0ZVY1S2RJS0V3Q05paGdXbDMwZ1FpY1VXSFRWR2I5VGZsMUdXcXM1bmRBOGdzRFJyc1V5UVN0KzV4TGEKWWU3UjhhNXU0a3hXQ3l0anFtbldQa0VDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkloWXJmTWUrYUd0eGw4bQpNNWw4a1M1Y1dHV3hNQjhHQTFVZEl3UVlNQmFBRkloWXJmTWUrYUd0eGw4bU01bDhrUzVjV0dXeE1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRVlSekc4WmplU1JJZDkzUDJ2SjRaeEIKeXg1M3Rzait0RVNKaHlITDFWUmhkUFhLYThHU2x3Z1Y3SXhmWXMvY0hSS1ZDRVpTOUVYR2Via3c2T3RpMHE4VwpNTnMxRit1MTlFWS9wc25FdDBHalVlRTFEVVNWWUVxcVVQSXlTbWZUdm9FUjVRNk5jaEZBSnhjS1BwMWUvSXBqCncxS3J0WWFNaGVqcms3R3JXZURWTUZoRGFzQzRaUHRFQ0J2aHRPSS9wVlhzSHBEUmJaUndUVDZPKzVPSUtZZjgKUXlaN3dRYTkrM3lXa0plZ1BpdERyU3l0MnFXYVUvNFlqb2RCeS9ZcWorREFVR1NUbWtVOFFuL25qQjJjeWE4WQp1OGhwNThaaG9CVkRPc204alozOGpweXI0YnlBMjR2OWpLUXE3bFVEaFF3Mkc4UzRsZlU3NUQ4OUVEcHJyd289Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: webhook
      namespace: system
      path: /validate-notification-kubesphere-io-v2beta2-config
  failurePolicy: Fail
  name: vconfig.notification.kubesphere.io
  rules:
  - apiGroups:
    - notification.kubesphere.io
    apiVersions:
    - v2beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - configs
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXekNDQWtPZ0F3SUJBZ0lVVG9uSE1YaFAzc2ljVHpQRHFmN1hmY2lLR1BZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1BERUxNQWtHQTFVRUJoTUNRMDR4Q3pBSkJnTlZCQWdNQWtoQ01Rc3dDUVlEVlFRS0RBSlJRekVUTUJFRwpBMVVFQXd3S2QyVmlhRzl2YXkxallUQWdGdzB5TVRBME1qRXdNalV5TlRsYUdBOHlNVEl4TURNeU9EQXlOVEkxCk9Wb3dQREVMTUFrR0ExVUVCaE1DUTA0eEN6QUpCZ05WQkFnTUFraENNUXN3Q1FZRFZRUUtEQUpSUXpFVE1CRUcKQTFVRUF3d0tkMlZpYUc5dmF5MWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQgpBSitpTWZQRld2dndWSmU1cUNBTWJlcnpaL0dLdFllZ3JRUlhES09nN1FKaE9nSWd5d25pKzVDM3VPM21JTE1hClRCWTkvcCtZM2d4akduUnJUWGNkcFB5ZG1BUDNyK2Y0Tm5TL3ZQa21XMm9mQzFNWEJNSUNUK1hFR3dIRExjWUgKR2hDWVBYcWVTZHVVTEJtTXFtYzFFNDB6ekRGcmpWTzltLzZFbjh0dVN3RmFaSVRnNUsvcm5Ld0UzdlNoazVYNApqVWdSYTF1Ym9nZHd1THFDTGRFWVB4MDdHUHdZb3JXQnlveXllYmNXRlBqRXRJSCtKWFRGQ2w0VDNXYkZhUUthCmxLOTY0ZVY1S2RJS0V3Q05paGdXbDMwZ1FpY1VXSFRWR2I5VGZsMUdXcXM1bmRBOGdzRFJyc1V5UVN0KzV4TGEKWWU3UjhhNXU0a3hXQ3l0anFtbldQa0VDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkloWXJmTWUrYUd0eGw4bQpNNWw4a1M1Y1dHV3hNQjhHQTFVZEl3UVlNQmFBRkloWXJmTWUrYUd0eGw4bU01bDhrUzVjV0dXeE1BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRVlSekc4WmplU1JJZDkzUDJ2SjRaeEIKeXg1M3Rzait0RVNKaHlITDFWUmhkUFhLYThHU2x3Z1Y3SXhmWXMvY0hSS1ZDRVpTOUVYR2Via3c2T3RpMHE4VwpNTnMxRit1MTlFWS9wc25FdDBHalVlRTFEVVNWWUVxcVVQSXlTbWZUdm9FUjVRNk5jaEZBSnhjS1BwMWUvSXBqCncxS3J0WWFNaGVqcms3R3JXZURWTUZoRGFzQzRaUHRFQ0J2aHRPSS9wVlhzSHBEUmJaUndUVDZPKzVPSUtZZjgKUXlaN3dRYTkrM3lXa0plZ1BpdERyU3l0MnFXYVUvNFlqb2RCeS9ZcWorREFVR1NUbWtVOFFuL25qQjJjeWE4WQp1OGhwNThaaG9CVkRPc204alozOGpweXI0YnlBMjR2OWpLUXE3bFVEaFF3Mkc4UzRsZlU3NUQ4OUVEcHJyd289Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: webhook
      namespace: system
      path: /validate-notification-kubesphere-io-v2beta2-receiver
  failurePolicy: Fail
  name: vreceiver.notification.kubesphere.io
  rules:
  - apiGroups:
    - notification.kubesphere.io
    apiVersions:
    - v2beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - receivers
