# permissions for end users to view emailreceivers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: emailreceiver-viewer-role
rules:
- apiGroups:
  - notification.kubesphere.io
  resources:
  - emailreceivers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - notification.kubesphere.io
  resources:
  - emailreceivers/status
  verbs:
  - get
