# permissions for end users to edit emailreceivers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: emailreceiver-editor-role
rules:
- apiGroups:
  - notification.kubesphere.io
  resources:
  - emailreceivers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notification.kubesphere.io
  resources:
  - emailreceivers/status
  verbs:
  - get
