# permissions for end users to view emailconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: emailconfig-viewer-role
rules:
- apiGroups:
  - notification.kubesphere.io
  resources:
  - emailconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - notification.kubesphere.io
  resources:
  - emailconfigs/status
  verbs:
  - get
