
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - notification.kubesphere.io
  resources:
  - EmailConfig
  - EmailReceiver
  - Receiver
  - SlackConfig
  - SlackReceiver
  - WebhookConfig
  - WebhookReceiver
  - WechatConfig
  - WechatReceiver
  - notificationmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notification.kubesphere.io
  resources:
  - notificationmanagers/status
  verbs:
  - get
  - patch
  - update
