# permissions for end users to edit slackconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slackconfig-editor-role
rules:
- apiGroups:
  - notification.kubesphere.io
  resources:
  - slackconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notification.kubesphere.io
  resources:
  - slackconfigs/status
  verbs:
  - get
