# permissions for end users to edit slackreceivers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slackreceiver-editor-role
rules:
- apiGroups:
  - notification.kubesphere.io
  resources:
  - slackreceivers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notification.kubesphere.io
  resources:
  - slackreceivers/status
  verbs:
  - get
