# permissions for end users to view slackreceivers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slackreceiver-viewer-role
rules:
- apiGroups:
  - notification.kubesphere.io
  resources:
  - slackreceivers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - notification.kubesphere.io
  resources:
  - slackreceivers/status
  verbs:
  - get
