# permissions for end users to view slackconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slackconfig-viewer-role
rules:
- apiGroups:
  - notification.kubesphere.io
  resources:
  - slackconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - notification.kubesphere.io
  resources:
  - slackconfigs/status
  verbs:
  - get
