# permissions for end users to edit webhookreceivers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhookreceiver-editor-role
rules:
- apiGroups:
  - notification.kubesphere.io
  resources:
  - webhookreceivers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notification.kubesphere.io
  resources:
  - webhookreceivers/status
  verbs:
  - get
