# permissions for end users to view webhookreceivers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhookreceiver-viewer-role
rules:
- apiGroups:
  - notification.kubesphere.io
  resources:
  - webhookreceivers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - notification.kubesphere.io
  resources:
  - webhookreceivers/status
  verbs:
  - get
