# permissions for end users to view wechatconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wechatconfig-viewer-role
rules:
- apiGroups:
  - notification.kubesphere.io
  resources:
  - wechatconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - notification.kubesphere.io
  resources:
  - wechatconfigs/status
  verbs:
  - get
