# permissions for end users to edit wechatreceivers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wechatreceiver-editor-role
rules:
- apiGroups:
  - notification.kubesphere.io
  resources:
  - wechatreceivers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notification.kubesphere.io
  resources:
  - wechatreceivers/status
  verbs:
  - get
