# permissions for end users to edit wechatconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wechatconfig-editor-role
rules:
- apiGroups:
  - notification.kubesphere.io
  resources:
  - wechatconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notification.kubesphere.io
  resources:
  - wechatconfigs/status
  verbs:
  - get
