# permissions for end users to view wechatreceivers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wechatreceiver-viewer-role
rules:
- apiGroups:
  - notification.kubesphere.io
  resources:
  - wechatreceivers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - notification.kubesphere.io
  resources:
  - wechatreceivers/status
  verbs:
  - get
