apiVersion: v1
data:
  password: dGVzdA==
kind: Secret
metadata:
  labels:
    app: notification-manager
  name: global-email-secret
  namespace: kubesphere-monitoring-system
type: Opaque
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: EmailConfig
metadata:
  labels:
    app: notification-manager
    scope: tenant
    user: admin
  name: admin-email-config
  namespace: kubesphere-monitoring-system
spec:
  authPassword:
    key: password
    name: global-email-secret
    namespace: kubesphere-monitoring-system
  authUsername: abc
  from: abc@xyz.com
  smartHost:
    host: imap.xyz.com
    port: "25"
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: EmailConfig
metadata:
  labels:
    app: notification-manager
    scope: global
  name: global-email-config
  namespace: kubesphere-monitoring-system
spec:
  authPassword:
    key: password
    name: global-email-secret
    namespace: kubesphere-monitoring-system
  authUsername: abc
  from: abc@xyz.com
  smartHost:
    host: imap.xyz.com
    port: "25"
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: EmailReceiver
metadata:
  labels:
    app: notification-manager
    scope: tenant
    user: admin
  name: admin-email
  namespace: kubesphere-monitoring-system
spec:
  emailConfigSelector:
    matchLabels:
      scope: tenant
      user: admin
  to:
  - abc2@xyz.com
  - abc3@xyz.com
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: NotificationManager
metadata:
  labels:
    app: notification-manager
  name: notificationmanager-sample
  namespace: kubesphere-monitoring-system
spec:
  global:
    configSelector:
      matchLabels:
        scope: global
  image: benjaminhuo/notification-manager:latest
  portName: webhook
  receivers:
    tenantKey: user
  replicas: 1
  serviceAccountName: default
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: SlackConfig
metadata:
  labels:
    app: notification-manager
    scope: global
  name: global-slack-config
  namespace: kubesphere-monitoring-system
spec:
  httpConfigSelector:
    matchLabels:
      scope: tenant
      user: admin
  slackApiUrl: slack_url_xxx
  slackApiUrlSecret:
    key: slack-api-url
    name: slack-api-url-secret
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: SlackReceiver
metadata:
  labels:
    app: notification-manager
    scope: tenant
    user: admin
  name: admin-slack
  namespace: kubesphere-monitoring-system
spec:
  channel: slack_channel_x
  slackConfigSelector:
    matchLabels:
      scope: tenant
      user: admin
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: WebhookConfig
metadata:
  labels:
    app: notification-manager
    scope: global
  name: global-webhook-config
  namespace: kubesphere-monitoring-system
spec:
  httpConfigSelector:
    matchLabels:
      scope: tenant
      user: admin
  url: xxx
  urlSecret:
    key: webhook-url
    name: webhook-url-secret
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: WebhookReceiver
metadata:
  labels:
    app: notification-manager
    scope: tenant
    user: admin
  name: admin-webhook
  namespace: kubesphere-monitoring-system
spec:
  webhookConfigSelector:
    matchLabels:
      scope: tenant
      user: admin
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: WechatConfig
metadata:
  labels:
    app: notification-manager
    scope: global
  name: global-wechat-config
  namespace: kubesphere-monitoring-system
spec:
  wechatApiCorpId: wechat-api-corp-id
  wechatApiSecret:
    key: wechat
    name: wechat-api-secret
  wechatApiUrl: wechat-api-url
---
apiVersion: notification.kubesphere.io/v1alpha1
kind: WechatReceiver
metadata:
  labels:
    app: notification-manager
    scope: tenant
    user: admin
  name: admin-wechat
  namespace: kubesphere-monitoring-system
spec:
  agentId: wechat-agent-id
  message: wechat-test-message
  toParty: wechat-party
  toTag: wechat-tag
  toUser: abc
  wechatConfigSelector:
    matchLabels:
      scope: tenant
      user: admin
