apiVersion: notification.kubesphere.io/v2alpha1
kind: EmailConfig
metadata:
  name: default-email-config
  labels:
    type: default
spec:
  from: sender1@xyz.com
  smartHost:
    host: imap.xyz.com
    port: "25"
  authUsername: sender1
  authPassword:
    name: default-email-secret
    key: password
  requireTLS: true
