apiVersion: notification.kubesphere.io/v1alpha1
kind: EmailConfig
metadata:
  name: default-email-config
  labels:
    type: default
spec:
  from: abc999@xyz.com
  smartHost:
    host: imap.xyz.com
    port: "25"
  authUsername: abc999
  authPassword:
    namespace: kubesphere-monitoring-system
    name: global-email-secret
    key: password
  requireTLS: true
