apiVersion: notification.kubesphere.io/v1alpha1
kind: WechatReceiver
metadata:
  name: user1-wechat
  labels:
    scope: tenant
    user: user1
spec:
  wechatConfigSelector:
    matchLabels:
      scope: tenant
      user: user1
  message: wechat-test-message
  agentId: wechat-agent-id
  toUser: benjamin
  toParty: wechat-party
  toTag: wechat-tag