apiVersion: notification.kubesphere.io/v1alpha1
kind: EmailReceiver
metadata:
  name: admin-email
  labels:
    scope: tenant
    user: admin
spec:
  to:
  - abc2@xyz.com
  - abc3@xyz.com
  emailConfigSelector:
    matchLabels:
      scope: tenant
      user: admin