apiVersion: notification.kubesphere.io/v1alpha1
kind: EmailConfig
metadata:
  name: global-email-config
  labels:
    scope: global
spec:
  from: abc@xyz.com
  smartHost:
    host: imap.xyz.com
    port: "25"
  authUsername: abc
  authPassword:
    namespace: kubesphere-monitoring-system
    name: global-email-secret
    key: password
  requireTLS: true
