apiVersion: notification.kubesphere.io/v1alpha1
kind: NotificationManager
metadata:
  name: notificationmanager-sample
spec:
  replicas: 1
  image: benjaminhuo/notification-manager:latest
  serviceAccountName: default
  portName: webhook
  globalConfigSelector:
    matchLabels:
      type: default
  receivers:
    tenantKey: user
    globalReceiverSelector:
      matchLabels:
        type: global
    tenantReceiverSelector:
      matchLabels:
        type: tenant