apiVersion: notification.kubesphere.io/v2alpha1
kind: Config
metadata:
  name: default-slack-config
  labels:
    type: default
spec:
  slack:
    slackTokenSecret:
      key: token
      name: slack-token-secret