apiVersion: notification.kubesphere.io/v2alpha1
kind: SlackConfig
metadata:
  name: default-slack-config
  labels:
    type: default
spec:
  slackTokenSecret:
    key: token
    name: slack-token-secret