apiVersion: notification.kubesphere.io/v2alpha1
kind: Receiver
metadata:
  name: global-slack-receiver
  labels:
    type: global 
spec:
  slack:
    slackConfigSelector:
      matchLabels:
        type: default
    channel: slack_channel_x
