# value of notification-manager-operator
operator: 
  containers:
    proxy:
      image:
        repo: kubesphere/kube-rbac-proxy
        tag: v0.4.1
        pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 50m
          memory: 30Mi
        requests:
          cpu: 50m
          memory: 30Mi
    operator:
      image:
        repo: kubesphere/notification-manager-operator
        tag: latest
        pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 50m
          memory: 30Mi
        requests:
          cpu: 50m
          memory: 30Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}


# value of notification-manager
notificationmanager:
  image:
    tag: latest
    pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 20Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  defaultConfigSelector:
    matchLabels:
      type: default
  receivers:
    tenantKey: user
    globalReceiverSelector:
      matchLabels:
        type: global
    tenantReceiverSelector:
      matchLabels:
        type: tenant
    options:
      email:
        notificationTimeout: 5
        deliveryType: bulk
      slack:
        notificationTimeout: 5
      wechat:
        notificationTimeout: 5
  notificationManagerNamespaces:
    - kubesphere-monitoring-system

