name: Publish to Dockerhub ( TENANT-SIDCAR )

on:
    workflow_dispatch:
      inputs:
        tags:
          description: 'Release Tags'

jobs:
    publish_dockerhub:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build and push Docker image 
              uses: docker/build-push-action@v3
              with:
                  context: ./sidecar/bytetrade
                  push: true
                  tags: bytetrade/notification-tenant-sidecar:${{ github.event.inputs.tags }}
                  file: ./sidecar/bytetrade/Dockerfile